---
  - name: "Application Jhub  Setup"
    hosts: localhost
    connection: local 
    tasks:
      - name: "Setup Envoy repo"
        get_url:
          url: https://getenvoy.io/linux/centos/tetrate-getenvoy.repo
          dest: /etc/yum.repos.d/envoy.repo
          mode: '0644'
      - name: "Install Python 3"
        yum:
          name: "{{ packages }}"
        vars:
           packages: 
           - python3
           - npm
           - yum-utils
      - name: "Enable Envoy Stable repo and Install Envoy"
        yum:
          name: getenvoy-envoy
          enablerepo: tetrate-getenvoy-stable
          state: present
      - name: "Install Jupyterhub and depended modules"
        pip:
          executable: /bin/pip3
          name: 
            - jupyterhub
            - notebook
            - npm
      - name: "Add jhub user"
        user:
          name: jhub
          comment: Jupyterhub user
          password: "$6$oRv7A/0fxveam4L4$HNJRgjtgu73z7QkxAdeWxdxeI5XhmvFQ3LUs/QsHPNLkfB49gz8LJqQ81WU5z1xBYMTgk0F/jkbvt6J.wuzvc"
      - name: "Install 'configurable-http-proxy' node.js package globally"
        npm:
          name: configurable-http-proxy
          global: yes
      - name: "Configuring Jupyterhub"
        command: "{{ item }}"
        with_items:
         - /usr/local/bin/jupyterhub --generate-config
        become: yes
        become_user: root
        args:
          chdir: /root
      - name: "Add bindurl config in Jupyterhub"
        replace:
          path: /root/jupyterhub_config.py
          after: 'c.JupyterHub.bind_url'
          replace: "c.JupyterHub.bind_url = 'http://127.0.0.1:8000'"
          regexp: '^#c.JupyterHub.bind_url.*$'
      - name: "Starting Jupyterhub"
        shell: nohup /usr/local/bin/jupyterhub --config /root/jupyterhub_config.py &
      - name: "Copy service definition file for jupyterhub"
        copy:
          src: /root/automation/app/jhub.json
          dest: /etc/consul.d/config/jhub.json
          owner: root
          group: root
          mode: '0644'
      - name: "Register jhub service in Consul"
        command: /usr/local/bin/consul services register /etc/consul.d/config/jhub.json
        become: yes
        become_user: root
      - name: "Start SideCar Envoy Proxy"
        command: consul connect envoy -sidecar-for jhub

