---
  - name: "Consul Server Setup"
    hosts: localhost
    connection: local 
    tasks:
     - name: "install necessary packages"
       yum:
           name: "{{ packages }}"
       tags:
          - common
     - name: "Download and setup consul"
       unarchive:
         src: https://releases.hashicorp.com/consul/1.7.2/consul_1.7.2_linux_amd64.zip
         dest: /usr/local/bin
         remote_src: yes
       tags:
          - common
     - name: "Verify consul installation"
       shell: "/usr/local/bin/consul --version"
       register: consul_version
       tags:
          - common
     - debug: var=consul_version.stdout_lines
       tags:
          - common
     - name: "Consul Config Directory"
       file: 
         path: "{{ item }}"
         state: directory
         mode: 'u=rwx,g=rx,o=rx'
       with_items:
         - '/etc/consul.d'
         - '/etc/consul.d/data'
         - '/etc/consul.d/config'
       tags:
          - common
     - name: "Copy Bootstrap configuration"
       copy:
        src: '/root/automation/consul/consul-server-bootstrap.json' 
        dest: '/etc/consul.d/config/config.json'
       tags:
          - consul-server
     - name: 'Setup startup script for consul server'
       copy:
        src: '/root/automation/consul/consul-server.service'
        dest: '/etc/systemd/system/consul.service'
       tags:
          - consul-server
     - name: "Copy Bootstrap configuration"
       copy:
        src: '/root/automation/consul/consul-agent-bootstrap.json' 
        dest: '/etc/consul.d/config/config.json'
       tags:
          - consul-agent
     - name: 'Setup startup script for consul server'
       copy:
        src: '/root/automation/consul/consul-agent.service'
        dest: '/etc/systemd/system/consul.service'
       tags:
          - consul-agent
     - name: "Copy Bootstrap configuration"
       copy:
        src: '/root/automation/consul/consul-client-bootstrap.json' 
        dest: '/etc/consul.d/config/config.json'
       tags:
          - consul-client
     - name: 'Setup startup script for consul client server'
       copy:
        src: '/root/automation/consul/consul-client.service'
        dest: '/etc/systemd/system/consul.service'
       tags:
          - consul-client
     - name: 'Start Consul Server' 
       systemd:
        name: consul.service
        state: started
       tags:
         - common