---
  - name: "Application Frontend  Setup"
    hosts: localhost
    connection: local 
    tasks:
      - name: "Install haproxy"
        yum:
          name: "{{ packages }}"
        vars:
          packages:
          - haproxy
      - name: "Setup Consul template"
        unarchive:
         src: https://releases.hashicorp.com/consul-template/0.24.1/consul-template_0.24.1_linux_amd64.zip
         dest: /usr/local/bin
         remote_src: yes
      - name: "Start Haproxy"
        shell: nohup /usr/local/bin/consul-template -config /root/automation/frontend/haproxy-ingress-config.hcl &
        

